"""Skill ontology: canonical skill -> surface variants, type, domains.
Hand-curated for the 24 resume categories in the corpus.
Type: T = technical/hard, S = soft/transferable.
"""

# canonical: (type, [variants beyond the canonical name])
ONTOLOGY = {
# ---------- Software / IT / Data ----------
"Python": ("T", ["python3", "py-thon"]),
"Java": ("T", ["core java", "java se", "j2ee", "java ee"]),
"JavaScript": ("T", ["java script", "js", "ecmascript", "node.js", "nodejs", "react.js", "reactjs", "angularjs", "angular", "vue.js"]),
"C++": ("T", ["cpp", "c ++"]),
"C#": ("T", ["c sharp", "csharp", "dot net", "asp.net", "vb.net"]),
"R Programming": ("T", ["r programming", "r language", "r studio", "rstudio"]),
"SQL": ("T", ["structured query language", "t-sql", "pl/sql", "plsql", "mysql", "postgresql", "postgres", "sql server", "oracle database", "ms sql"]),
"NoSQL": ("T", ["mongodb", "cassandra", "dynamodb", "couchdb", "redis"]),
"Machine Learning": ("T", ["ml algorithms", "machine-learning", "predictive modeling", "predictive modelling", "supervised learning", "unsupervised learning", "scikit-learn", "sklearn"]),
"Deep Learning": ("T", ["neural network", "neural networks", "cnn", "rnn", "lstm", "transformer model"]),
"Natural Language Processing": ("T", ["nlp", "text mining", "sentiment analysis", "text analytics"]),
"Computer Vision": ("T", ["image processing", "opencv", "image recognition"]),
"TensorFlow": ("T", ["tensor flow", "keras"]),
"PyTorch": ("T", ["py torch", "torch framework"]),
"Data Analysis": ("T", ["data analytics", "data analysis", "analytical skills", "statistical analysis", "quantitative analysis", "pandas", "numpy"]),
"Data Visualization": ("T", ["tableau", "power bi", "powerbi", "qlikview", "matplotlib", "data visualisation", "dashboards", "dashboard development"]),
"Big Data": ("T", ["hadoop", "apache spark", "apache hive", "kafka", "mapreduce", "big data analytics"]),
"Statistics": ("T", ["statistical modeling", "regression analysis", "hypothesis testing", "probability", "biostatistics"]),
"Cloud Computing": ("T", ["aws", "amazon web services", "azure", "google cloud", "gcp", "cloud platform", "cloud infrastructure"]),
"DevOps": ("T", ["ci/cd", "jenkins", "docker", "kubernetes", "terraform", "ansible", "continuous integration"]),
"Linux": ("T", ["unix", "ubuntu", "red hat", "shell scripting", "bash scripting"]),
"Networking": ("T", ["tcp/ip", "lan/wan", "network administration", "cisco", "routers and switches", "firewall", "vpn"]),
"Cybersecurity": ("T", ["information security", "network security", "penetration testing", "vulnerability assessment", "siem", "iso 27001"]),
"Web Development": ("T", ["html", "css", "html5", "front-end development", "back-end development", "full stack", "full-stack", "web application development"]),
"Mobile Development": ("T", ["android development", "ios development", "swift programming", "kotlin", "react native", "flutter"]),
"Software Testing": ("T", ["qa testing", "quality assurance testing", "selenium", "test automation", "unit testing", "regression testing", "manual testing"]),
"Version Control": ("T", ["git", "github", "svn", "bitbucket", "subversion"]),
"API Development": ("T", ["rest api", "restful", "soap", "web services", "graphql", "microservices"]),
"System Administration": ("T", ["windows server", "active directory", "vmware", "server administration", "it support", "help desk", "technical support"]),
"ERP Systems": ("T", ["sap", "oracle erp", "peoplesoft", "workday system", "netsuite", "dynamics 365"]),
"Business Intelligence": ("T", ["bi tools", "data warehouse", "data warehousing", "etl", "informatica", "ssis", "ssrs"]),
"Agile Methodology": ("T", ["scrum", "kanban", "sprint planning", "agile development", "safe agile"]),
"Software Development Life Cycle": ("T", ["sdlc", "waterfall model", "software engineering"]),
"Microsoft Office": ("T", ["ms office", "microsoft word", "ms excel", "microsoft excel", "powerpoint", "ms outlook", "excel spreadsheets", "advanced excel", "pivot tables", "vlookup"]),

# ---------- Finance / Accounting / Banking ----------
"Financial Analysis": ("T", ["financial modeling", "financial modelling", "variance analysis", "ratio analysis", "financial planning and analysis", "fp&a"]),
"Accounting": ("T", ["general ledger", "journal entries", "bookkeeping", "account reconciliation", "accounts payable", "accounts receivable", "ap/ar", "trial balance"]),
"Financial Reporting": ("T", ["financial statements", "balance sheet", "profit and loss", "p&l", "month-end close", "year-end close"]),
"GAAP": ("T", ["generally accepted accounting principles", "us gaap", "ifrs"]),
"Auditing": ("T", ["internal audit", "external audit", "audit compliance", "sox", "sarbanes-oxley"]),
"Taxation": ("T", ["tax returns", "tax preparation", "income tax", "gst", "vat", "tax compliance"]),
"Budgeting": ("T", ["budget preparation", "budget management", "cost control", "forecasting", "cost accounting"]),
"Payroll": ("T", ["payroll processing", "payroll administration", "adp payroll"]),
"QuickBooks": ("T", ["quick books", "tally", "sage accounting"]),
"Banking Operations": ("T", ["retail banking", "teller operations", "branch operations", "cash handling", "kyc", "know your customer"]),
"Credit Analysis": ("T", ["credit risk", "underwriting", "loan processing", "credit appraisal", "mortgage lending"]),
"Investment Management": ("T", ["portfolio management", "asset management", "equity research", "wealth management", "mutual funds"]),
"Risk Management": ("T", ["risk assessment", "risk mitigation", "operational risk", "market risk"]),
"Anti-Money Laundering": ("T", ["aml", "bsa compliance", "fraud detection", "fraud investigation"]),
"Treasury Management": ("T", ["cash flow management", "cash management", "liquidity management"]),

# ---------- Engineering / Construction / Automobile / Aviation / Agriculture ----------
"AutoCAD": ("T", ["auto cad", "autodesk", "2d drafting", "cad drafting", "technical drafting"]),
"SolidWorks": ("T", ["solid works", "creo", "catia", "pro/engineer"]),
"Mechanical Design": ("T", ["mechanical engineering", "design engineering", "product design", "gd&t", "tolerance analysis"]),
"Electrical Systems": ("T", ["electrical engineering", "circuit design", "wiring diagrams", "plc", "scada", "instrumentation"]),
"Civil Engineering": ("T", ["structural engineering", "structural analysis", "staad pro", "surveying", "geotechnical"]),
"Project Estimation": ("T", ["cost estimation", "quantity takeoff", "bill of quantities", "tendering", "bidding"]),
"Construction Management": ("T", ["site supervision", "site management", "construction supervision", "subcontractor management", "punch list"]),
"Building Codes": ("T", ["osha standards", "safety codes", "building regulations", "permits and inspections"]),
"CNC Machining": ("T", ["cnc programming", "lathe", "milling", "machining", "fabrication"]),
"Welding": ("T", ["mig welding", "tig welding", "arc welding", "soldering"]),
"Preventive Maintenance": ("T", ["predictive maintenance", "equipment maintenance", "troubleshooting equipment", "breakdown maintenance", "machine repair"]),
"Lean Manufacturing": ("T", ["six sigma", "5s", "kaizen", "continuous improvement", "value stream mapping", "tpm"]),
"Quality Control": ("T", ["quality assurance", "qa/qc", "inspection", "iso 9001", "root cause analysis", "capa"]),
"Automotive Repair": ("T", ["engine repair", "brake systems", "transmission repair", "vehicle diagnostics", "obd", "automotive service"]),
"Aircraft Maintenance": ("T", ["airframe", "powerplant", "a&p license", "avionics", "line maintenance", "aircraft inspection"]),
"Flight Operations": ("T", ["flight planning", "air traffic", "faa regulations", "commercial pilot", "pilot license", "crew scheduling", "aviation safety"]),
"Agronomy": ("T", ["crop management", "soil analysis", "soil science", "irrigation", "crop rotation", "pest management", "agricultural production"]),
"Livestock Management": ("T", ["animal husbandry", "dairy management", "poultry management", "veterinary support"]),
"Farm Equipment": ("T", ["tractor operation", "harvesting equipment", "farm machinery"]),

# ---------- Healthcare ----------
"Patient Care": ("T", ["patient assessment", "direct patient care", "bedside care", "patient education", "vital signs"]),
"Clinical Documentation": ("T", ["emr", "ehr", "epic systems", "cerner", "medical records", "charting", "meditech"]),
"Medical Coding": ("T", ["icd-9", "icd-10", "cpt coding", "medical billing", "hcpcs"]),
"HIPAA Compliance": ("T", ["hipaa", "patient privacy", "phi"]),
"Nursing": ("T", ["registered nurse", "rn license", "lpn", "cna", "nursing care", "bls", "acls"]),
"Pharmacy": ("T", ["pharmacology", "medication administration", "prescription processing", "pharmacy technician"]),
"Medical Terminology": ("T", ["anatomy and physiology", "clinical terminology"]),
"Laboratory Testing": ("T", ["phlebotomy", "specimen collection", "lab procedures", "diagnostic testing"]),
"Case Management": ("T", ["care coordination", "discharge planning", "utilization review", "treatment planning"]),
"Physical Therapy": ("T", ["rehabilitation", "therapeutic exercise", "occupational therapy"]),

# ---------- HR / Legal / Consulting / PR / Business ----------
"Recruitment": ("T", ["talent acquisition", "sourcing candidates", "full-cycle recruiting", "applicant tracking system", "ats", "interviewing candidates", "screening resumes", "onboarding"]),
"Employee Relations": ("T", ["labor relations", "grievance handling", "conflict resolution", "disciplinary action", "employee engagement"]),
"HR Policies": ("T", ["hr policies", "policy development", "employee handbook", "hr compliance", "eeo", "fmla"]),
"Compensation and Benefits": ("T", ["benefits administration", "compensation planning", "salary benchmarking", "401k", "open enrollment"]),
"HRIS": ("T", ["hr information system", "workday hcm", "successfactors", "hris"]),
"Training and Development": ("T", ["learning and development", "employee training", "training programs", "instructional design", "curriculum development"]),
"Performance Management": ("T", ["performance reviews", "performance appraisal", "kpi tracking", "goal setting"]),
"Legal Research": ("T", ["westlaw", "lexisnexis", "case law research", "legal analysis"]),
"Litigation": ("T", ["trial preparation", "depositions", "pleadings", "discovery process", "motions", "court proceedings"]),
"Contract Drafting": ("T", ["contract negotiation", "contract review", "contract management", "agreements drafting"]),
"Regulatory Compliance": ("T", ["compliance management", "statutory compliance", "regulatory affairs", "due diligence"]),
"Intellectual Property": ("T", ["patent", "trademark", "copyright law"]),
"Business Analysis": ("T", ["requirements gathering", "gap analysis", "business requirements", "process mapping", "use cases", "user stories"]),
"Process Improvement": ("T", ["business process improvement", "workflow optimization", "operational efficiency", "process reengineering"]),
"Strategic Planning": ("T", ["business strategy", "strategic initiatives", "go-to-market", "market entry", "corporate strategy"]),
"Market Research": ("T", ["market analysis", "competitive analysis", "competitor analysis", "consumer research", "survey design", "focus groups"]),
"Public Relations": ("T", ["media relations", "press releases", "press release", "crisis communication", "publicity", "media outreach"]),
"Event Management": ("T", ["event planning", "event coordination", "trade shows", "conference planning", "event execution"]),
"Content Writing": ("T", ["copywriting", "content creation", "editorial", "blog writing", "technical writing", "proofreading"]),
"Social Media Marketing": ("T", ["social media management", "facebook marketing", "instagram marketing", "linkedin marketing", "twitter marketing", "social media campaigns"]),
"Digital Marketing": ("T", ["seo", "search engine optimization", "sem", "google analytics", "google ads", "ppc", "email marketing", "marketing automation", "hubspot"]),
"Brand Management": ("T", ["branding", "brand strategy", "brand identity", "brand awareness"]),
"Campaign Management": ("T", ["marketing campaigns", "advertising campaigns", "campaign execution", "media planning"]),

# ---------- Sales / BD / Retail / BPO ----------
"Sales Strategy": ("T", ["sales planning", "sales forecasting", "territory management", "sales targets", "quota attainment"]),
"Lead Generation": ("T", ["prospecting", "cold calling", "lead qualification", "pipeline development", "outbound sales"]),
"CRM Software": ("T", ["salesforce", "crm systems", "zoho crm", "microsoft dynamics crm", "siebel"]),
"Account Management": ("T", ["key account management", "client relationship management", "client retention", "portfolio of accounts"]),
"Negotiation": ("S", ["deal negotiation", "negotiating contracts", "closing deals"]),
"Business Development": ("T", ["new business development", "partnership development", "channel development", "b2b sales", "b2c sales"]),
"Customer Service": ("T", ["customer support", "customer satisfaction", "client servicing", "customer experience", "service delivery"]),
"Call Center Operations": ("T", ["inbound calls", "outbound calls", "call handling", "average handling time", "bpo operations", "voice process", "tele calling"]),
"Retail Operations": ("T", ["store operations", "merchandising", "visual merchandising", "inventory management", "stock management", "pos systems", "loss prevention"]),
"Supply Chain": ("T", ["logistics", "procurement", "vendor management", "purchasing", "warehouse management", "distribution management", "shipping and receiving"]),

# ---------- Design / Arts / Media / Apparel ----------
"Graphic Design": ("T", ["visual design", "layout design", "print design", "typography"]),
"Adobe Creative Suite": ("T", ["adobe photoshop", "photoshop", "illustrator", "indesign", "adobe xd", "after effects", "premiere pro", "coreldraw"]),
"UI/UX Design": ("T", ["user experience design", "user interface design", "wireframing", "prototyping", "figma", "sketch app", "usability testing"]),
"Video Production": ("T", ["video editing", "final cut pro", "videography", "motion graphics", "post-production"]),
"Photography": ("T", ["photo editing", "studio photography", "photo shoots"]),
"3D Modeling": ("T", ["3d rendering", "maya", "blender", "3ds max", "cad modeling"]),
"Interior Design": ("T", ["space planning", "interior decoration", "furniture design"]),
"Fashion Design": ("T", ["apparel design", "garment construction", "pattern making", "sketching designs", "textile design", "tech pack"]),
"Merchandise Planning": ("T", ["assortment planning", "range planning", "buying and merchandising", "sourcing vendors"]),
"Quality Inspection Apparel": ("T", ["fabric inspection", "garment quality", "aql inspection"]),
"Performing Arts": ("T", ["choreography", "stage performance", "theatre production", "music performance", "dance instruction"]),
"Curriculum Design": ("T", ["lesson planning", "syllabus development", "course design", "instructional planning"]),
"Classroom Management": ("T", ["student assessment", "classroom instruction", "differentiated instruction", "iep", "student engagement"]),
"Educational Technology": ("T", ["smart board", "learning management system", "lms", "blackboard", "moodle", "google classroom"]),

# ---------- Fitness / Chef / Hospitality ----------
"Personal Training": ("T", ["fitness training", "strength training", "exercise programming", "workout plans", "group fitness"]),
"Nutrition Counseling": ("T", ["diet planning", "nutrition planning", "meal planning", "dietary guidance"]),
"Fitness Assessment": ("T", ["body composition", "fitness evaluation", "physical assessment"]),
"CPR Certification": ("T", ["cpr", "first aid certified", "aed"]),
"Culinary Arts": ("T", ["food preparation", "cooking techniques", "recipe development", "menu development", "menu planning", "plating"]),
"Kitchen Management": ("T", ["kitchen operations", "line cook", "sous chef", "executive chef", "banquet", "catering"]),
"Food Safety": ("T", ["haccp", "servsafe", "sanitation standards", "food handling", "food hygiene"]),
"Cost of Goods Control": ("T", ["food cost control", "portion control", "inventory costing"]),
"Hospitality Management": ("T", ["hotel operations", "front office", "guest relations", "reservations", "housekeeping management"]),

# ---------- Soft / transferable ----------
"Communication": ("S", ["verbal communication", "written communication", "communication skills", "interpersonal skills", "presentation skills"]),
"Leadership": ("S", ["team leadership", "leading teams", "people management", "supervisory", "mentoring", "coaching staff"]),
"Teamwork": ("S", ["collaboration", "team player", "cross-functional teams", "working in teams"]),
"Problem Solving": ("S", ["troubleshooting", "critical thinking", "analytical thinking", "root cause identification"]),
"Time Management": ("S", ["prioritization", "meeting deadlines", "multitasking", "multi-tasking", "organizational skills"]),
"Adaptability": ("S", ["flexibility", "fast-paced environment", "change management"]),
"Attention to Detail": ("S", ["detail-oriented", "detail oriented", "meticulous", "high level of accuracy"]),
"Decision Making": ("S", ["judgment", "decision-making"]),
"Customer Focus": ("S", ["client-focused", "customer-focused", "customer oriented"]),
"Project Management": ("T", ["pmp", "project planning", "project coordination", "ms project", "jira", "project delivery", "stakeholder management"]),
}

# Domains each canonical skill is most associated with (for job authoring sanity only)
AMBIGUOUS_SKIP = {" r ", " c ", " go ", " d "}   # never matched as bare tokens
